name             'CIS_CentOS7_v1.1.0_level_2'
maintainer       'Conor Lee'
maintainer_email 'ConorLee@outlook.com'
license          'MIT License'
description      'Installs/Configures CIS_CentOS7_v1.1.0_level_2'
long_description 'Installs/Configures CIS_CentOS7_v1.1.0_level_2'
version          '0.1.0'
